repos:
  # Example of basic pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict

  # Add a hook for secrets detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0  # Use the latest stable version
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]

  # Example of a Python-specific hook
  - repo: https://github.com/psf/black
    rev: 24.10.0  # Use the latest stable version
    hooks:
      - id: black
